//ACTIONS USER
export const FETCH_USERS="FETCH_USERS";
export const INSERT_USER="INSERT_USER";
export const UPDATE_USER="UPDATE_USER";
export const DELETE_USER="DELETE_USER";
export const SET_SHOW_ALERT="SET_SHOW_ALERT";